config/routes.rb
Rails.application.routes.draw do
  
  root "pages#welcome"
  get "/portfolio" => "pages#portfolio"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def welcome
end

end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <header>
    <%= link_to "Portfolio", portfolio_path %>
    <%= link_to "Welcome", root_path %>
    This is the header
  </header>
  <br>
<body>

<%= yield %>

</body>
  <footer>
    This is the footer
  </footer>
</html>

app/views/pages/portfolio.html.erb
<!DOCTYPE html>
<html>
  <p> This is the portfolio page. </p>

app/views/pages/welcome.html.erb
<!DOCTYPE html>
<html>
  <main>
    <div> This is the welcome page.
    </div>
  </main>
  